// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv9_asdrhSvOZV8AmEZF3y9YvDxpwhKlU',
    appId: '1:1095146268192:web:7366428685f50254797e45',
    messagingSenderId: '1095146268192',
    projectId: 'todo-4540d',
    authDomain: 'todo-4540d.firebaseapp.com',
    storageBucket: 'todo-4540d.appspot.com',
    measurementId: 'G-9YYN58C3R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqnzn9WRoGJYGk4Ic_c_DnI4k989vtRQ4',
    appId: '1:1095146268192:android:ed3f3f7b6b08de61797e45',
    messagingSenderId: '1095146268192',
    projectId: 'todo-4540d',
    storageBucket: 'todo-4540d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLg1KOhnfI9iGUR2sQ2HyYdR3nQE6h4e8',
    appId: '1:1095146268192:ios:94bd2d965b60a47c797e45',
    messagingSenderId: '1095146268192',
    projectId: 'todo-4540d',
    storageBucket: 'todo-4540d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLg1KOhnfI9iGUR2sQ2HyYdR3nQE6h4e8',
    appId: '1:1095146268192:ios:94bd2d965b60a47c797e45',
    messagingSenderId: '1095146268192',
    projectId: 'todo-4540d',
    storageBucket: 'todo-4540d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv9_asdrhSvOZV8AmEZF3y9YvDxpwhKlU',
    appId: '1:1095146268192:web:3ac9c85dd3850ebb797e45',
    messagingSenderId: '1095146268192',
    projectId: 'todo-4540d',
    authDomain: 'todo-4540d.firebaseapp.com',
    storageBucket: 'todo-4540d.appspot.com',
    measurementId: 'G-72KX3LSXC6',
  );
}
